name: Deploy static content to Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_PROJECT_VERSION: ${{ github.run_number }}
        run: npm run build
        
      - name: Setup Pages
        if: github.event_name == 'workflow_dispatch'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        if: github.event_name == 'workflow_dispatch'
        id: deployment
        uses: actions/deploy-pages@v4
